version: "3.8"

services:
#  database:
#    container_name: storage-problem
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=storage_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
#    volumes:
#      - redis:/data
volumes:
  postgres:
